apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: se1n81vb4-go 
  janus-idp.io/tekton: se1n81vb4-go
  backstage.io/kubernetes-id: se1n81vb4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: se1n81vb4-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml